### PR TITLE
Close card implementation

### PR DESCRIPTION
**Pull request by ForNeVeR**
Here is the implementation for card archival.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Thank you!

**Comment by ForNeVeR** [comment]
Hey, could you also open issues on this repository? I have some stuff I'd want to discuss, but currently trello4j haven't any places for public discussions or bug tracking :(

**Comment by johanmynhardt** [comment]
@ForNeVeR Done! :) Sorry that I only got around to it now.

**Comment by ForNeVeR** [comment]
No, thank you, that's not a problem :)

**Pull request merged**
